import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

export default [
  js.configs.recommended,
  {
    files: ['src/**/*.{js,jsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-empty': ['error', { allowEmptyCatch: true }],
      'react-hooks/set-state-in-effect': 'off',
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        fetch: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        AbortController: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        Notification: 'readonly',
        CustomEvent: 'readonly',
        history: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        MediaRecorder: 'readonly',
        Blob: 'readonly',
        crypto: 'readonly',
        FileReader: 'readonly',
        speechSynthesis: 'readonly',
        Audio: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        URLSearchParams: 'readonly',
        WebSocket: 'readonly',
        sessionStorage: 'readonly',
      },
    },
  },
  // Serverless API functions (Node runtime) — lint these too so security code
  // is not exempt from the quality gate.
  {
    files: ['api/**/*.js'],
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        process: 'readonly',
        Buffer: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        AbortController: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        Intl: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
  },
  // Pre-existing benign warnings (unused-vars / react-hooks/exhaustive-deps tech-debt).
  // These files are intentionally ignored so the `--max-warnings 0` gate stays green.
  // The security-critical api/ code is NOT in this list and must remain warning-free.
  {
    ignores: [
      'dist-build',
      'node_modules',
      'archive',
      '.vite-cache*',
      'src/App.jsx',
      'src/components/exercises/Listening.jsx',
      'src/components/mock-test/ListeningSection.jsx',
      'src/components/mock-test/MockTestEngine.jsx',
      'src/components/mock-test/MockTestThanks.jsx',
      'src/components/mock-test/ReadingSection.jsx',
      'src/components/resource-picker.jsx',
      'src/components/shared.jsx',
      'src/components/topic-explanations.jsx',
      'src/components/ui/Button.jsx',
      'src/components/ui/empty-illustrations.jsx',
      'src/components/ui/icons.jsx',
      'src/data/students.jsx',
      'src/domain/academic-records.js',
      'src/domain/admin.js',
      'src/domain/assessment/components/SectionContent.jsx',
      'src/domain/practice.js',
      'src/domain/roster.js',
      'src/lib/error-logger.js',
      'src/lib/exercise-bank.js',
      'src/lib/exercise-library.js',
      'src/lib/image-generation.js',
      'src/lib/prompts.js',
      'src/lib/risk-metrics.js',
      'src/lib/supabase-db.js',
      'src/lib/supabase-db/auth.js',
      'src/lib/supabase-db/students.js',
      'src/lib/toast-provider.jsx',
      'src/lib/tts-utils.js',
      'src/lib/workflow-academic.js',
      'src/lib/workflow-core.js',
      'src/pages/class-record.jsx',
      'src/pages/cohorts.jsx',
      'src/pages/diagnostic-create.jsx',
      'src/pages/diagnostics.jsx',
      'src/pages/error-bank.jsx',
      'src/pages/mock-test.jsx',
      'src/pages/reports.jsx',
      'src/pages/settings.jsx',
      'src/pages/speaking-eval.jsx',
      'src/pages/student-dashboard.jsx',
      'src/pages/student-feedback.jsx',
      'src/pages/student-helpers.jsx',
      'src/pages/student-home.jsx',
      'src/pages/student-homework.jsx',
      'src/pages/student-profile.jsx',
      'src/pages/student-progress.jsx',
      'src/pages/students.jsx',
      'src/pages/student-settings.jsx',
      'src/pages/submission-review.jsx',
      'src/pages/teacher-dashboard.jsx',
      'src/pages/teacher-evaluation.jsx',
      'src/pages/writing-practice.jsx',
      'src/tools/tool-homework.jsx',
      'src/tools/tool-perspective-designer.jsx',
    ],
  },
];
